(* Special symbols *)

(* $Date: 2011-03-02 14:21:03 -0500 (Wed, 02 Mar 2011) $ *)

(* This file defines some HTML symbols, for use by coqdoc... *)

(** printing || #<span style="font-family: arial;">&dArr;</span># *)
(** printing ==> #<span style="font-family: arial;">&rArr;</span># *)
(** printing ==>* #<span style="font-family: arial;">&rArr;*</span># *)
(** printing ==>+ #<span style="font-family: arial;">&rArr;+</span># *)
(** printing -> #<span style="font-family: arial;">&rarr;</span># *)
(** printing <- #<span style="font-family: arial;">&larr;</span># *)
(** printing <-> #<span style="font-family: arial;">&harr;</span># *)
(** printing forall #<span style="font-family: arial;">&forall;</span># *)
(** printing exists #<span style="font-family: arial;">&exist;</span># *)
(** printing /\ #<span style="font-family: arial;">&and;</span># *)
(** printing \/ #<span style="font-family: arial;">&or;</span># *)
(** printing ~~> #<span style="font-family: arial;">&#8658;</span># *)
(** printing <~~> #<span style="font-family: arial;">&#8660;</span># *)
(** printing |- #<span style="font-family: arial;">&#8866;</span># *)
(** printing Gamma #<span style="font-family: serif; font-size:85%;">&Gamma;</span># *)
(* The following are added by Japanese translators *)
(** printing Gamma' #<span style="font-family: serif; font-size:85%;">&Gamma;'</span># *)
